version: '2'
services:
    jpualgo-app:
        image: jpualgo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jpualgo-postgresql:5432/jpualgo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jpualgo-postgresql:
        extends:
            file: postgresql.yml
            service: jpualgo-postgresql
